### ISSUE TITLE
3: Level Editor

### ISSUE THREAD

**Issue by CameronJ2** [CameronJ2/Summit-Sprint#10]
Level editor for making new levels going forward. May even allow users to create their own levels

**Comment by Karmanic25** [comment]
test comment

**Comment by CameronJ2** [comment]
Hey Jacob, I moved this issue to sprint 4 instead of 2. This is a pretty big undertaking that might take a while, but it shouldn't be your primary focus for now. Try and keep most of your working time focused around the current sprint if possible
